### PR TITLE
Update to netstandard2.0 framework

### PR DESCRIPTION
**Pull request by burtonr**
This updates the `sln` and `csproj` files to target netstandard2.0 framework. 

No functional changes. All tests still pass.

### CODE REVIEW

**Comment by kinetiq** [comment]
This is great, thank you. I didn't know people were actually using this!

**Comment by burtonr** [comment]
Great news! Thanks for putting this together. We had done a similar version, but not nearly as fast, or accurate, but we're on .NET Core... 

FYI, I removed the commit where I edited the readme file saying it's not published. So that it can be merged back up now. 

Thanks!

**Comment by kinetiq** [comment]
I am really glad people like it. Thanks for the contribution, I will do a nuget release shortly.

**Comment by kinetiq** [comment]
The nuget package for 1.2.0 is out, confirmed working in a little console application. Thanks again!

**Comment by burtonr** [comment]
That's awesome! Thanks for the mention as well!

**Pull request merged**
